import type {Metadata} from "next";
import {Roboto_Flex} from "next/font/google";
import "./globals.css";

const robotoFlex = Roboto_Flex({
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}; //поменять в конце

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={robotoFlex.className}>
        <body id="__next">
            {children}
        </body>
        </html>
    );
}
